version: "3"

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.9.2
    hostname: wazuh.manager
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - ./rules:/var/ossec/etc/rules/custom
      - ./decoders:/var/ossec/etc/decoders/custom
      - ./tests/logs:/var/ossec/logs/testing
